### ISSUE TITLE
the batch_size of output tensor is 1, not equal to that of input tensor

### ISSUE THREAD

**Issue by jjrCN** [tatp22/multidim-positional-encoding#2]
![屏幕快照 2021-03-19 下午5 08 38](https://user-images.githubusercontent.com/37108754/111756972-c8034080-88d5-11eb-9893-0030d42d4974.png)
the input tensor batchsize is 16 but output is 1.

**Comment by tatp22** [comment]
Hi @jjrCN!

I'll take a look at it later today, I'll get back to you. I didn't test this actually, good catch

**Comment by jjrCN** [comment]
> Hi @jjrCN!
> 
> I'll take a look at it later today, I'll get back to you. I didn't test this actually, good catch

well,thank you very much

**Comment by tatp22** [comment]
Should be fixed, check out version `3.0.0`, or just pull the latest one from here.

This was a strange bug. Also, I'm surprised no one opened up an issue earlier about all of `PositionalEncoding{1,2,3}D` failing to import, due to me messing up the `__init__.py`. (That's also fixed now)
