### ISSUE TITLE
torch.cat operation of sin() and cos does() not gives same result as formula

### ISSUE THREAD

**Issue by bguetarni** [tatp22/multidim-positional-encoding#20]
According to the formula :
```
PE(x,2i) = sin(x/10000^(2i/D))
PE(x,2i+1) = cos(x/10000^(2i/D))
```

the final positional encoding vector should have sine values in even dimensions and cosine values in odd dimension.
However, in your [code](https://github.com/tatp22/multidim-positional-encoding/blob/master/positional_encodings/positional_encodings.py#L34) you do a simple concatenation, which results in sine values for the first half dimensions and cosine values for the rest.

For example let's consider a batch size of 1 and a sequence of length 1. If I use `inv_freq` as a vector of zeros I should at the end get an encoding vector with 0 for even dimensions ( sin(0)=0 ) and 1 for odd dimensions ( cos(0)=1 ). However when we use the code provided in the class `PositionalEncoding1D` we end up with a vector that has 0 in the first half and 1 in the other half; which is due to the simple concatenation. The code below reproduce this:
```
shape = (1, 1, 10)
channels = 10
channels = int(np.ceil(channels / 2) * 2)
inv_freq = torch.zeros(int(channels/2))
batch_size, x, orig_ch = shape
pos_x = torch.arange(x)
sin_inp_x = torch.einsum("i,j->ij", pos_x, inv_freq)
emb_x = torch.cat((sin_inp_x.sin(), sin_inp_x.cos()), dim=-1)
emb = torch.zeros((x, channels))
emb[:, :channels] = emb_x
```

result :
`tensor([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])`

The following change correct this error :
```
emb_x = torch.stack((sin_inp_x.sin(), sin_inp_x.cos()), dim=-1)
emb_x = torch.flatten(emb_x, -2, -1)
```
result :
`tensor([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])
`

It creates a stacked tensor with sine and cosine pairs (with same dimension) and flatten it so that we have sine values in `2i` and cosine values in `2i + 1`.

**Comment by tatp22** [comment]
Hey @bguetarni!

Thanks for the catch. Indeed, this isn't as stated in the formula. I can get a PR to fix this and assign you as a reviewer if you want to take a look before i release.

**Comment by bguetarni** [comment]
Please, could you take a look on [this commit on my fork](https://github.com/bguetarni/multidim-positional-encoding/commit/3e57367690639d940b047408f75ae726e5973fac). All the tests pass for this one.

**Comment by tatp22** [comment]
Looks good to me. Do you want to make a pr here? I can update the pypi package afterwards as well.

**Comment by bguetarni** [comment]
[Opened one](https://github.com/tatp22/multidim-positional-encoding/pull/22)

**Comment by tatp22** [comment]
Thanks for the fix

**Comment by tatp22** [comment]
Hm, still one formatting check issue. Ill fix this when I can.
