### ISSUE TITLE
Installing this package seems to force installation of tensorflow.

### ISSUE THREAD

**Issue by curt-tigges** [tatp22/multidim-positional-encoding#24]
When installing this via `pip install positional-encodings` the installer automatically downloads and attempts to install tensorflow. This is undesirable for some users who are using pytorch instead.

**Comment by tatp22** [comment]
Hi @curt-tigges! You're right, this is undesirable. I think that the best thing to do is to change the package such that it is installed something like this:

```
pip install positional-encodings[pytorch,tensorflow]
```

This would install the package as it is, with the option for the user to take what they want.

**Comment by tatp22** [comment]
Should be fixed with `6.0.1`, check out the new installation docs on the readme to get it just for `torch`

**Comment by curt-tigges** [comment]
Thanks, seems resolved!
