### ISSUE TITLE
Using TFPositionalEncoding2D in model

### ISSUE THREAD

**Issue by mpost** [tatp22/multidim-positional-encoding#29]
We are experimenting with the integration of the `TFPositionalEncoding2D` into a custom model and would like some advice on the topic.

We saw that for the 1D version (`TFPositionalEncoding1D`) several people have embedded their input vector into an `Embedding` layer and feed that to the `TFPositionalEncoding1D`. Eg.

```python
# declaration
self.position_embedding = Embedding(input_dim=vocab_size, output_dim=output_dim)
self.position_encoding = TFPositionalEncoding1D(output_dim)

# usage
position_embedding = self.position_embedding(inputs)
embedded_indices = self.position_encoding(position_embedding)
return position_embedding + embedded_indices
```

If this would be the correct approach to use the 1D encoding, how could this be translated to feed the 2D version? It would require an `Embedding` that produces `(batch_size, x, y, channels)` wich is not possible in TF. Any advice would be appreciated.

**Comment by gsg213** [comment]
Hello @mpost,

You would need to use then two different embeddings, one for x and y, or columns and rows. Then, concat these embeddings to have the size that you need.

Hope it helps!
