### ISSUE TITLE
the parameter:  channels !!!

### ISSUE THREAD

**Issue by STAROFWIND** [tatp22/multidim-positional-encoding#3]
Hi all, 
I am trying to use function: PositionalEncodingPermute2D
I have a input:  torch.Size([1, 169, 1, 1024])
So, the "channels" will be 169
But the error: RuntimeError: The expanded size of the tensor (85) must match the existing size (86) at non-singleton dimension 2.  Target sizes: [1, 1024, 85].  Tensor sizes: [86]
I also find that if channels%4 == {1,2} ---> the error happens. 
So can you explain what I am missing here ? 
Thank you so much !!!

**Comment by tatp22** [comment]
Hi @STAROFWIND,

I'll investigate this and get back to you.

**Comment by tatp22** [comment]
Hey,

Thanks for finding this bug. I just fixed this with the latest pr; if you wanna get this via pip just download version 4.0.0.
I also fixed this for the 3d case, if that was also a problem.

**Comment by STAROFWIND** [comment]
I also fixed this bug myself. Just add index for emb_X and emb_y. 
Thank you so much for your great job !!!
