### ISSUE TITLE
Use PositionalEncoding1D without batches?

### ISSUE THREAD

**Issue by ChristianVaughn** [tatp22/multidim-positional-encoding#30]
Is there a reason the positional encoding functions require the input data to be in a 3d batch form? Trying to use this with a model that doesn't do batch processing and was wondering if it could be done, or if i am better off implementing my own positional encoding class?

**Comment by tatp22** [comment]
Hey @ChristianVaughn,

It's true I made this primarily for batch processing. However, if you want to use this without batch processing, you can probably still use my class like this (some pseudocode):

```
class PEncWithoutBatch:
  def __init__(penc: PositionalEncoding1DMatrix):
    # Here penc is what you would get from the forward call ie penc = pe(your_tensor)
    self.penc = penc
  
  def forward(tensor):
    return self.penc.reshape([self.penc.shape[1], self.penc.shape[2]])
```

And then you'd use it as follows:

```
original_penc = PositionalEncoding1D(channels)
your_penc_class_you_want = PEncWithoutBatch(original_penc(tensor))
new_penc_without_batch = your_penc_class_you_want(tensor)
```

Well, something like that would be the rough draft.

**Comment by ChristianVaughn** [comment]
Thanks for the suggestion. I think this would do what I was trying to do
